name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install TypeScript
      run: npm install
    - name: Run tests
      run: sbt ts2mlsJS/test
    - name: Check no changes
      run: git diff-files -p --exit-code --diff-filter=ADMR -w